package com.canja.kutowerdefence.domain;

public enum Option {
    WAVE_NUMBER,
    WAVE_DELAY,
    WAVE_GROUP_DELAY,
    ENEMY_SPAWN_DELAY,
    GOLD,
    GOBLIN_REWARD,
    KNIGHT_REWARD,
    ARCHER_TOWER_COST,
    ARTILLERY_TOWER_COST,
    MAGE_TOWER_COST,
    PLAYER_HITPOINT,
    GOBLIN_HITPOINT,
    KNIGHT_HITPOINT,
    ARROW_DAMAGE,
    ARTILLERY_DAMAGE,
    SPELL_DAMAGE,
    TOWER_RANGE,
    AOE_RANGE,
    GOBLIN_SPEED,
    KNIGHT_SPEED
}
