package com.canja.kutowerdefence.domain;

public enum TileType {
    CIRCULAR_TOPLEFT,
    CIRCULAR_TOPCENTER,
    CIRCULAR_TOPRIGHT,
    TOP,
    CIRCULAR_CENTERLEFT,
    EMPTY,
    CIRCULAR_CENTERRIGHT,
    VERTICAL,
    CIRCULAR_BOTTOMLEFT,
    CIRCULAR_BOTTOMCENTER,
    CIRCULAR_BOTTOMRIGHT,
    BOTTOM,
    LEFT,
    HORIZONTAL,
    RIGHT,
    EMPTY_LOT,
    // object tiles below
    TREE1,
    TREE2,
    TREE3,
    ROCK1,
    TOWER_ARTILLERY,
    TOWER_MAGE,
    HOUSE,
    ROCK2,
    CASTLE1,
    CASTLE2,
    TOWER_ARCHER,
    WELL,
    CASTLE3,
    CASTLE4,
    FORTRESS,
    LOGS,
    WAY1,
    WAY2,
    WAY3,
    WAY4
}