package com.canja.kutowerdefence.domain;

public enum TileType {
    HORIZONTAL,
    VERTICAL,
    CIRCULAR_TOPLEFT,
    CIRCULAR_TOPCENTER,
    CIRCULAR_TOPRIGHT,
    CIRCULAR_CENTERLEFT,
    CIRCULAR_CENTER,
    CIRCULAR_CENTERRIGHT,
    CIRCULAR_BOTTOMLEFT,
    CIRCULAR_BOTTOMCENTER,
    CIRCULAR_BOTTOMRIGHT,
}
